### ISSUE TITLE
Vue 2.5.10. Got Duplicate keys error.

### ISSUE THREAD

**Issue by webrsb** [icebob/vue-touch-keyboard#15]
Hi, I got Duplicate keys error since update to latest vue.
It worked fine Less than 2.5.10.
Reproduction Link: [https://jsfiddle.net/5brbuv8a/](https://jsfiddle.net/5brbuv8a/)

**Comment by jruuska** [comment]
The problem seems to be that "key" property is not correctly bound here https://github.com/icebob/vue-touch-keyboard/blob/master/src/keyboard.vue#L5;L6 but instead the elements get repeatedly assigned the same key `"index"` instead the actual value of `index` variable.

Changing `key="index"` to `:key="index"` should fix the error.

**Comment by webrsb** [comment]
Close via #17
